export const getDefaultCalendar = () => {
  return [
    {
      id: '20/11',
      jogos: [
        {
          mandante: 'qatar',
          golsMandante: '0',
          horario: '13:00',
          visitante: 'ecuador',
          golsVisitante: '2',
        },
      ],
    },
    {
      id: '21/11',
      jogos: [
        {
          mandante: 'england',
          golsMandante: '',
          horario: '10:00',
          visitante: 'iran',
          golsVisitante: '',
        },
        {
          mandante: 'senegal',
          golsMandante: '',
          horario: '13:00',
          visitante: 'netherlands',
          golsVisitante: '',
        },
        {
          mandante: 'united_states',
          golsMandante: '',
          horario: '16:00',
          visitante: 'wales',
          golsVisitante: '',
        },
      ],
    },
    {
      id: '22/11',
      jogos: [
        {
          mandante: 'argentina',
          golsMandante: '',
          horario: '07:00',
          visitante: 'saudi_arabia',
          golsVisitante: '',
        },
        {
          mandante: 'denmark',
          golsMandante: '',
          horario: '10:00',
          visitante: 'tunisia',
          golsVisitante: '',
        },
        {
          mandante: 'mexico',
          golsMandante: '',
          horario: '13:00',
          visitante: 'poland',
          golsVisitante: '',
        },
        {
          mandante: 'france',
          golsMandante: '',
          horario: '16:00',
          visitante: 'australia',
          golsVisitante: '',
        },
      ],
    },
    {
      id: '23/11',
      jogos: [
        {
          mandante: 'marocco',
          golsMandante: '',
          horario: '07:00',
          visitante: 'croatia',
          golsVisitante: '',
        },
        {
          mandante: 'germany',
          golsMandante: '',
          horario: '10:00',
          visitante: 'japan',
          golsVisitante: '',
        },
        {
          mandante: 'spain',
          golsMandante: '',
          horario: '13:00',
          visitante: 'costa_rica',
          golsVisitante: '',
        },
        {
          mandante: 'belgium',
          golsMandante: '',
          horario: '16:00',
          visitante: 'canada',
          golsVisitante: '',
        },
      ],
    },
    {
      id: '24/11',
      jogos: [
        {
          mandante: 'switzerland',
          golsMandante: '',
          horario: '07:00',
          visitante: 'cameroon',
          golsVisitante: '',
        },
        {
          mandante: 'uruguay',
          golsMandante: '',
          horario: '10:00',
          visitante: 'south_korea',
          golsVisitante: '',
        },
        {
          mandante: 'portugal',
          golsMandante: '',
          horario: '13:00',
          visitante: 'ghana',
          golsVisitante: '',
        },
        {
          mandante: 'brazil',
          golsMandante: '',
          horario: '16:00',
          visitante: 'serbia',
          golsVisitante: '',
        },
      ],
    },
    {
      id: '25/11',
      jogos: [
        {
          mandante: 'wales',
          golsMandante: '',
          horario: '07:00',
          visitante: 'iran',
          golsVisitante: '',
        },
        {
          mandante: 'qatar',
          golsMandante: '',
          horario: '10:00',
          visitante: 'senegal',
          golsVisitante: '',
        },
        {
          mandante: 'netherlands',
          golsMandante: '',
          horario: '13:00',
          visitante: 'ecuador',
          golsVisitante: '',
        },
        {
          mandante: 'england',
          golsMandante: '',
          horario: '16:00',
          visitante: 'united_states',
          golsVisitante: '',
        },
      ],
    },
    {
      id: '26/11',
      jogos: [
        {
          mandante: 'tunisia',
          golsMandante: '',
          horario: '07:00',
          visitante: 'australia',
          golsVisitante: '',
        },
        {
          mandante: 'poland',
          golsMandante: '',
          horario: '10:00',
          visitante: 'saudi_arabia',
          golsVisitante: '',
        },
        {
          mandante: 'france',
          golsMandante: '',
          horario: '13:00',
          visitante: 'denmark',
          golsVisitante: '',
        },
        {
          mandante: 'argentina',
          golsMandante: '',
          horario: '16:00',
          visitante: 'mexico',
          golsVisitante: '',
        },
      ],
    },
    {
      id: '27/11',
      jogos: [
        {
          mandante: 'japan',
          golsMandante: '',
          horario: '07:00',
          visitante: 'costa_rica',
          golsVisitante: '',
        },
        {
          mandante: 'belgium',
          golsMandante: '',
          horario: '10:00',
          visitante: 'marocco',
          golsVisitante: '',
        },
        {
          mandante: 'croatia',
          golsMandante: '',
          horario: '13:00',
          visitante: 'canada',
          golsVisitante: '',
        },
        {
          mandante: 'spain',
          golsMandante: '',
          horario: '16:00',
          visitante: 'germany',
          golsVisitante: '',
        },
      ],
    },
    {
      id: '28/11',
      jogos: [
        {
          mandante: 'cameroon',
          golsMandante: '',
          horario: '07:00',
          visitante: 'serbia',
          golsVisitante: '',
        },
        {
          mandante: 'south_korea',
          golsMandante: '',
          horario: '10:00',
          visitante: 'ghana',
          golsVisitante: '',
        },
        {
          mandante: 'brazil',
          golsMandante: '',
          horario: '13:00',
          visitante: 'switzerland',
          golsVisitante: '',
        },
        {
          mandante: 'portugal',
          golsMandante: '',
          horario: '16:00',
          visitante: 'uruguay',
          golsVisitante: '',
        },
      ],
    },
    {
      id: '29/11',
      jogos: [
        {
          mandante: 'ecuador',
          golsMandante: '',
          horario: '12:00',
          visitante: 'senegal',
          golsVisitante: '',
        },
        {
          mandante: 'netherlands',
          golsMandante: '',
          horario: '12:00',
          visitante: 'qatar',
          golsVisitante: '',
        },
        {
          mandante: 'iran',
          golsMandante: '',
          horario: '16:00',
          visitante: 'united_states',
          golsVisitante: '',
        },
        {
          mandante: 'wales',
          golsMandante: '',
          horario: '16:00',
          visitante: 'england',
          golsVisitante: '',
        },
      ],
    },
    {
      id: '30/11',
      jogos: [
        {
          mandante: 'tunisia',
          golsMandante: '',
          horario: '12:00',
          visitante: 'france',
          golsVisitante: '',
        },
        {
          mandante: 'australia',
          golsMandante: '',
          horario: '12:00',
          visitante: 'denmark',
          golsVisitante: '',
        },
        {
          mandante: 'poland',
          golsMandante: '',
          horario: '16:00',
          visitante: 'argentina',
          golsVisitante: '',
        },
        {
          mandante: 'saudi_arabia',
          golsMandante: '',
          horario: '16:00',
          visitante: 'mexico',
          golsVisitante: '',
        },
      ],
    },
    {
      id: '01/12',
      jogos: [
        {
          mandante: 'croatia',
          golsMandante: '',
          horario: '12:00',
          visitante: 'belgium',
          golsVisitante: '',
        },
        {
          mandante: 'canada',
          golsMandante: '',
          horario: '12:00',
          visitante: 'marocco',
          golsVisitante: '',
        },
        {
          mandante: 'japan',
          golsMandante: '',
          horario: '16:00',
          visitante: 'spain',
          golsVisitante: '',
        },
        {
          mandante: 'costa_rica',
          golsMandante: '',
          horario: '16:00',
          visitante: 'germany',
          golsVisitante: '',
        },
      ],
    },
    {
      id: '02/12',
      jogos: [
        {
          mandante: 'south_korea',
          golsMandante: '',
          horario: '12:00',
          visitante: 'portugal',
          golsVisitante: '',
        },
        {
          mandante: 'ghana',
          golsMandante: '',
          horario: '12:00',
          visitante: 'uruguay',
          golsVisitante: '',
        },
        {
          mandante: 'serbia',
          golsMandante: '',
          horario: '16:00',
          visitante: 'switzerland',
          golsVisitante: '',
        },
        {
          mandante: 'cameroon',
          golsMandante: '',
          horario: '16:00',
          visitante: 'brazil',
          golsVisitante: '',
        },
      ],
    },
  ];
};
